### ISSUE TITLE
close button not working

### ISSUE THREAD

**Issue by genbu** [SelenGora/TurkeyMap#5]
on line 131
			$('#spinner').hide();
			/* @author: Taner DOGAN //START */	
			$(".close").live("click",function(){  ---------------> live is not a function
				$("#detail").css("display", "none").empty();	
                                 .......................

but when I change into "on" instead "live", no error but close button not working, help, thx.

**Comment by tanerdogan** [comment]
jQuery doesn't support "live" anymore, you're right method must call  "on" and its creating elements "live" on the DOM. Correct solution must be;

`$("body").on("click", ".close", function()`

* I didn't tested.

**Comment by genbu** [comment]
great! .. thank you ...
